### ISSUE TITLE
BIDs validation fails on previously validated dataset

### ISSUE THREAD

**Issue by annchenruth** [BIDS-Apps/HCPPipelines#59] opened 2020-07-17 17:46 UTC
I'm working on using the recently released docker container for HCPpipeline v4.1.3 to process the HCP-Aging dataset.  I've converted the dataset to BIDs format to the point that it passes validation with the BIDs validator docker app.  However, inside the HCP container, validation fails with this message:

bids-validator /cifs/hariri-long/Studies/HCP-Aging/BIDS/sourcedata
        ESC[31m1: Files with such naming scheme are not part of BIDS specification. This error is most commonly caused by typos in file names that make them not BIDS compatible. Please consult the specification and make sure your files are named correctly. If this is not a file naming issue (for example when including files not yet covered by the BIDS specification) you should include a ".bidsignore" file in your dataset. Please note that derived (processed) data should be placed in /derivatives folder and source data (such as DICOMS or behavioural logs in proprietary formats) should be placed in the /sourcedata folder. (code: 1 - NOT_INCLUDED)ESC[39m

                ./sub-6005242/func/sub-6005242_task-carit_dir-PA_bold.json
                ./sub-6005242/func/sub-6005242_task-facename_dir-PA_bold.nii.gz
                ./sub-6005242/func/sub-6005242_task-vismotor_dir-PA_bold.nii.gz
...
[plus a jillion more files]

Is there something I seem to be missing here?  Thanks!

**Comment by rhancockn** [comment] 2020-07-20 19:22
From the output, it looks like you are using an older version of the container (pre 4.1.3). The 4.1.3 version can currently be pulled from `rhancock/hcpbids` on DockerHub. Sorry about this-I know there are some inconsistencies in which container to pull, which I will soon correct. I tested the older `bids/hcppipelines` on a sample tree and can reproduce your error, but the validation step succeeds on the newer `rhancock/hcpbids` image. The files you list do have valid BIDS names, so it remains a mystery why validation fails with the older version. There is also a `--skip_bids_validation` flag to the container.

**Comment by annchenruth** [comment] 2020-07-21 15:23
Ah, thanks for clearing that up and for all your work on this!  I did get past validation after I re-built my singularity container from `rhancock/hcpbids`, but hit another error pretty quickly.  I have a thread going on neurorstars with details on that so I'll just link to it rather than duplicate here: https://neurostars.org/t/processing-hcp-aging-dataset-in-bids-format/15164/4

**Comment by rhancockn** [comment] 2020-07-21 17:39
Closing to continue discussion on neurostars.

**Closed by rhancockn** 2020-07-21 17:39 UTC
